config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#top"
  get 'home/about', to: 'home#about', as: 'about'

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :update, :create, :new, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  has_one_attached :profile_image

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:name]

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :public_action]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  before_action :set_book

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.build(book_comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = "コメントを投稿しました"
    else
      flash[:danger] = "コメントを投稿できませんでした"
    end
    redirect_to book_path(@book)
  end

  def destroy
    @comment = @book.book_comments.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      redirect_to @book, notice: 'コメントが削除されました。'
    else
      redirect_to @book, alert: 'コメントの削除に失敗しました。'
    end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:book_comment).permit(:comment)
  end

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

  def correct_user
    comment = BookComment.find(params[:id])
    unless comment.user_id == current_user.id
      flash[:danger] = "権限がありません"
      redirect_to book_path(comment.book)
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = BookComment.new
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :profile_image)
    end

    def correct_user
      @book = Book.find(params[:id])
      redirect_to(books_path) unless current_user == @book.user
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :find_book

  def create
    @favorite = current_user.favorites.new(book_id: @book.id)
    if @favorite.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path, alert: 'いいねに失敗しました。')
    end
  end

  def destroy
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    if @favorite.destroy
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path, alert: 'いいねの削除に失敗しました。')
    end
  end

  private

  def find_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
    @comment = BookComment.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_leftcommon.html.erb
 <!-- 左側 -->
<div class="col-md-3">
  <h2>User info</h2>
  <!-- ユーザーごとの画像を表示させたい（ユーザーの画像がない場合は、app/assets/images/noimage.pngを表示させる）-->
  <%= image_tag(user.profile_image.attached? ? user.profile_image : 'noimage.png', class: 'img-fluid') %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <td><!-- ユーザーの名前をここに表示させたい（Userモデルのnameというカラム） -->
          <%= user.name %>
        </td>
      </tr>
      <tr>
        <th>introduction</th>
        <td><!-- ユーザーの自己紹介（Userモデルのintroductionというカラムを表示させたい） -->
          <%= user.introduction %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
      <i class="fa-solid fa-user-gear" style="color: 7d7d7d"></i>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <!-- Bookモデルのtitleカラムに入力できるようなフォームを作りたい-->
  <%= form_with model: book, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :body, 'Opinion' %>
      <%= f.text_area :body, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <%= form_with(model: @book, local: true) do |form| %>
          <div class="form-group">
            <h1>Editing Book</h1>
            <% if @book.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
                <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= form.label :title, class: "control-label" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>

            <p></p>

            <div class="field">
              <%= form.label :body, "Opinion", class: "control-label" %>
              <%= form.text_area :body, class: "form-control" %>
            </div>

            <p></p>

            <div class="actions">
              <%= form.submit "Update Book", class: "btn btn-success" %>
            </div>
          </div>
        <% end %>

        <%= link_to 'Show', @book, class: "btn btn-link btn-sm" %> |
        <%= link_to 'Back', books_path, class: "btn btn-link btn-sm" %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p></p>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'leftcommon', locals: { user: @user, book: @book } %>
      <!-- 右側 -->
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |b| %>
              <tr>
                <td><!-- Bookモデルに投稿したユーザーの画像（Userモデルの画像）を表示させたい-->
                  <%= link_to user_path(b.user) do %>
                    <%= image_tag(b.user.profile_image.attached? ? b.user.profile_image : 'noimage.png', style: 'width: 100px; height: 100px;', class: 'img-fluid') %>
                  <% end %>
                </td>
                <td>
                  <%= link_to b.title, book_path(b) %>
                </td>
                <td>
                  <%= b.body %>
                </td>
                <td>
                  <% if b.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(b), method: :delete do %>
                      <i class="fa-solid fa-heart text-danger"></i><span class="text-danger"><%= b.favorites.count %></span>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(b), method: :post do %>
                      <i class="fa-solid fa-heart text-primary"></i><span class="text-primary"><%= b.favorites.count %></span>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <p>コメント数: <%= b.book_comments.count %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<main>
  <p></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'leftcommon', locals: { user: @user, book: @newbook } %>
      <!-- 右側 -->
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">

          <tbody>
            <tr>
              <td>
                <%= link_to(@book.user) do %>
                  <%= image_tag(@book.user.profile_image.attached? ? @book.user.profile_image : 'noimage.png', style: 'width: 100px; height: 85px;', class: 'img-fluid') %>
                <% end %>
                </br><a><%= link_to @book.user.name, @book.user %></a>
              </td>
              <td><%= link_to @book.title, book_path(@book) %></td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <i class="fa-solid fa-heart text-danger"></i><span class="text-danger">1</span>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <i class="fa-solid fa-heart text-primary"></i><span class="text-primary">0</span>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= @book.book_comments.count %></p>
              </td>
              <td>
                <% if current_user == @book.user %>
                  <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-success btn-sm' %>
                  <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn btn-danger btn-sm' %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>


        <table>
          <thread>
            <tr>
              <th></th>
            </tr>
          </thread>
          <tbody>
          <% @book.book_comments.each do |comment| %>
            <tr>
              <td>
                <p>
                  <%= image_tag(comment.user.profile_image.attached? ? comment.user.profile_image : 'noimage.png', style: 'width: 80px; height: 60px;', class: 'img-fluid rounded-circle') %>
                   </br><strong><%= link_to comment.user.name, comment.user %></strong>
                </p>
              </td>
              <td>
                <p><%= comment.comment %></p>
              </td>
              <td>
                <% if comment.user == current_user %>
                  <%= link_to 'Destroy', book_book_comment_path(@book, comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn btn-danger btn-sm' %>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div>
          <%= form_with(model: [@book, @book.book_comments.build], local: true) do |f| %>
            <div class="form-group">
              <%= f.text_area :comment, class: "form-control" %>
            </div>
            <%= f.submit "送信", class: "btn btn-sm btn-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/home/about.html.erb
<main>
  <p> </p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to <i class="fa-solid fa-book" style="color: FFFFFF"></i>
        <strong>Bookers</strong> !!
      </h1>
      </h1>
    </div>
  </div>
</main>

app/views/home/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <p></p>
        <h1>Welcome to <i class="fa-solid fa-book" style="color: FFFFFF"></i>
          <strong>Bookers</strong> !!
        </h1>
        <p>In <i class="fa-solid fa-book" style="color: FFFFFF"></i><strong>Bookers</strong>,</p>
        <p>you can share and excahnge your opinions, inpressions, and emotions</p>
        <p>about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">
              Log in
            </a>
          </div>

          <div class="row">
            <a class="btn btn-success btn-sm btn-block mb-3 sign_up" href="/users/sign_up">
              Sign up
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/1474896bbd.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand p-3" href="/">
          <span>Bookers</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                  <i class="fa-solid fa-house" style="color: #FFFFFF"></i>
                  Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-users" style="color: #FFFFFF"></i>
                  Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-book-open" style="color: #FFFFFF"></i>
                  Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-right-from-bracket" style="color: #FFFFFF"></i>
                  Log out
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-house" style="color: #FFFFFF"></i>
                  Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-link" style="color: #FFFFFF"></i>
                  About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-user-plus" style="color: #FFFFFF"></i>
                  Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-right-to-bracket" style="color: #FFFFFF"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </header>
    <div class="container">
      <%= yield %>
    </div>

    <main>

    </main>


    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <%= form_with(model: @user, local: true) do |f| %>
          <div class="form-group">
            <h1>User info</h1>
            <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h2>
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= f.label :name, class: "control-label" %>
              <%= f.text_field :name, class: "form-control" %>
            </div>

            <p></p>

            <div class="field">
              <%= f.label :profile_image, class: "control-label" %></br>
              <%= f.file_field :profile_image %>
            </div>

            <p></p>

            <div class="field">
              <%= f.label :introduction, class: "control-label" %>
              <%= f.text_area :introduction, class: "form-control" %>
            </div>

            <p></p>

            <div class="actions">
              <%= f.submit "Update User", class: "btn btn-success" %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'books/leftcommon', locals: { user: @user, book: @book } %>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse" width="100%">
          <thead>
            <tr>
              <th width="30%">image</th>
              <th width="40%">name</th>
              <th colspan="3", width="30%"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |u| %>
              <tr>
                <td>
                  <%= image_tag(u.profile_image.attached? ? u.profile_image : 'noimage.png', style: 'width: 120px; height: 100px;', class: 'img-fluid') %>
                </td>
                <td>
                  <%= u.name %>
                </td>
                <td>
                  <a>
                    <%= link_to 'Show', user_path(u) %>
                  </a>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'books/leftcommon', locals: { user: @user, book: @book } %>
      <!-- 右側 -->
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse" width="100%">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |b| %>
              <tr>
                <td>
                  <%= link_to @user do %>
                    <%= image_tag(@user.profile_image.attached? ? @user.profile_image : 'noimage.png', style: 'width: 100px; height: 85px;', class: 'img-fluid') %>
                  <% end %>
                </td>
                <td><%= link_to b.title, book_path(b) %></td>
                <td><%= b.body %></td>
                <td>
                  <% if b.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorites_path(b), method: :delete do %>
                        <i class="fa-solid fa-heart text-danger"></i><span class="text-danger">1</span>
                      <% end %>
                    </p>
                  <% else %>
                    <p>
                      <%= link_to book_favorites_path(b), method: :post do %>
                        <i class="fa-solid fa-heart text-primary"></i><span class="text-primary">0</span>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <td>
                  <p>コメント数: <%= b.book_comments.count %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>